# Generated by Django 3.0.2 on 2020-01-29 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('year', models.DateField()),
                ('engine', models.IntegerField(default=0)),
                ('gearbox', models.CharField(max_length=50)),
                ('ad_date', models.CharField(max_length=50)),
                ('ad_url', models.URLField()),
            ],
            options={
                'verbose_name': 'Car',
                'verbose_name_plural': 'Cars',
            },
        ),
    ]
