# Generated by Django 3.0.2 on 2020-01-29 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbase',
            name='ad_date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='carbase',
            name='ad_url',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='carbase',
            name='engine',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='carbase',
            name='price',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='carbase',
            name='year',
            field=models.CharField(max_length=100),
        ),
    ]
